name: CI

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  cancel:
    name: "Cancel Previous Runs"
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.13.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

  build:
    needs: cancel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Restore Lean cache
        uses: actions/cache/restore@v5
        with:
          path: ./.lake
          key: ${{ runner.os }}-lean-ci-${{ hashFiles('lake-manifest.json') }}
          restore-keys: |
            ${{ runner.os }}-lean-ci-
            ${{ runner.os }}-lean-docs-${{ hashFiles('lake-manifest.json') }}
            ${{ runner.os }}-lean-docs-

      - uses: leanprover/lean-action@v1.4.0
        with:
          lint: false
          use-github-cache: false
